services:
  back:
    image: directus/directus:11.12
    container_name: "rocking_horse_directus"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8055:8055
    volumes:
      - ./backend/uploads:/directus/uploads
      - ./backend/extensions:/directus/extensions
    env_file: .env
    networks:
      - rhp
    restart: unless-stopped

  db:
    image: postgres:16
    platform: linux/amd64
    container_name: "rocking_horse_postgres"
    ports:
      - 5432:5432
    volumes:
      - ./db/data:/var/lib/postgresql/data
    env_file: .env
    networks:
      - rhp
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  rhp:
    name: rhp
    driver: bridge
